import type { ResearchQueueSnapshot } from "./model";

export const demoQueueSnapshot: ResearchQueueSnapshot = {
  generatedAt: "2026-07-15T08:42:00Z",
  knowledgeCutoffAt: "2026-07-14T20:00:00Z",
  universeCount: 4,
  eligibleCount: 4,
  returnedCount: 4,
  isTruncated: false,
  candidates: [
    {
      id: "US:NXTC",
      market: "US",
      ticker: "NXTC",
      company: "NextCure, Inc.",
      sector: "Biotechnology",
      capTier: "micro",
      currency: "USD",
      price: 8.42,
      dailyChangePct: 3.8,
      priority: 93,
      status: "needs_review",
      owner: "Maya Chen",
      queueReason: "Cash-runway assumptions changed while price structure remains early.",
      keyChange:
        "The latest evidence pack changes the estimated financing window and introduces a near-term clinical readout dependency.",
      thesisSummary:
        "The setup is interesting only if the next milestone preserves strategic optionality without an expensive financing event.",
      invalidation:
        "Liquidity weakens below the mandate floor, the catalyst window moves, or disclosed financing capacity becomes insufficient.",
      catalyst: { label: "Clinical update", window: "5 days", daysAway: 5, confidence: "inferred" },
      factors: { quality: 58, value: 76, momentum: 67, risk: 72 },
      evidence: {
        freshness: "fresh",
        sourceCount: 18,
        counterCount: 4,
        coveragePct: 91,
        knownAt: "2026-07-14T20:00:00Z",
        items: [
          {
            id: "nxtc-10q",
            source: "SEC",
            title: "Quarterly filing and liquidity disclosures",
            publishedAt: "2026-07-12",
            purpose: "supporting",
            confidence: "primary",
          },
          {
            id: "nxtc-trial",
            source: "Clinical registry",
            title: "Study status and milestone window",
            publishedAt: "2026-07-13",
            purpose: "context",
            confidence: "primary",
          },
          {
            id: "nxtc-risk",
            source: "SEC",
            title: "Financing and going-concern language differential",
            publishedAt: "2026-07-12",
            purpose: "counter",
            confidence: "derived",
          },
        ],
      },
      liquidity: { averageDailyValue: "$2.8m", capacity: "$185k", exitDays: 2.4 },
      researchClues: [
        {
          key: "reported_accumulation_near_low",
          title: "Reported accumulation near yearly low",
          summary:
            "The completed-session close is 8.4% above its 52-week low. In the 2026-06-30 Form 13F period, 9 managers reported new/increased positions versus 3 reduced/exited positions (net breadth +50%).",
          dataAsOf: "2026-06-30",
          publicAsOf: "2026-07-14",
          limitations: [
            "Form 13F is delayed and excludes shorts, trade dates, execution prices, and manager intent.",
            "Manager breadth reduces raw-share denominator distortion but does not prove coordinated or current buying.",
          ],
        },
      ],
      flags: ["Financing dependency", "Event concentration"],
      scenarios: [
        { id: "bear", value: 4.6, returnPct: -45, premise: "Catalyst delay and discounted financing." },
        { id: "base", value: 10.1, returnPct: 20, premise: "Milestone lands inside the current cash window." },
        { id: "bull", value: 15.8, returnPct: 88, premise: "Positive data expands the addressable program." },
      ],
      sparkline: [6.1, 6.4, 6.2, 6.8, 7.1, 6.9, 7.4, 7.8, 7.6, 8.1, 8.42],
    },
    {
      id: "DSE:BSC",
      market: "DSE",
      ticker: "BSC",
      company: "Bangladesh Shipping Corporation",
      sector: "Services & Real Estate",
      capTier: "mid",
      currency: "BDT",
      price: 124.2,
      dailyChangePct: 3.4,
      priority: 89,
      status: "new_evidence",
      owner: "Arif Rahman",
      queueReason: "Fresh disclosure changes the earnings and fleet-utilization debate.",
      keyChange:
        "A new official disclosure creates a material evidence differential versus the previous operating assumptions.",
      thesisSummary:
        "The research case depends on whether operating improvement is durable after separating one-off effects.",
      invalidation:
        "Normalized earnings fail to improve or the next official update contradicts the utilization thesis.",
      catalyst: { label: "Board disclosure", window: "3 days", daysAway: 3, confidence: "confirmed" },
      factors: { quality: 63, value: 82, momentum: 78, risk: 44 },
      evidence: {
        freshness: "fresh",
        sourceCount: 24,
        counterCount: 3,
        coveragePct: 95,
        knownAt: "2026-07-14T12:30:00Z",
        items: [
          {
            id: "bsc-dse",
            source: "DSE",
            title: "Latest material company disclosure",
            publishedAt: "2026-07-14",
            purpose: "supporting",
            confidence: "primary",
          },
          {
            id: "bsc-fin",
            source: "DSE",
            title: "Reported financial trajectory",
            publishedAt: "2026-06-30",
            purpose: "context",
            confidence: "primary",
          },
          {
            id: "bsc-volume",
            source: "Market data",
            title: "Participation and implementation-liquidity review",
            publishedAt: "2026-07-14",
            purpose: "counter",
            confidence: "derived",
          },
        ],
      },
      liquidity: { averageDailyValue: "৳4.1cr", capacity: "৳18.4l", exitDays: 1.8 },
      researchClues: [
        {
          key: "reported_accumulation_near_low",
          title: "Reported accumulation near yearly low",
          summary:
            "The completed-session close is 6.2% above its 52-week low, while the reported institutional ownership category increased +0.40 percentage points from the prior disclosure.",
          dataAsOf: "2026-06-30",
          publicAsOf: null,
          limitations: [
            "DSE ownership is a delayed category percentage; it does not identify buyers, trades, prices, or intent.",
            "The source stores the reporting period but not a trustworthy publication timestamp, so this clue is excluded from historical point-in-time strategy claims.",
          ],
        },
      ],
      flags: ["Government-linked", "One-off normalization"],
      scenarios: [
        { id: "bear", value: 91, returnPct: -27, premise: "Operating gain proves temporary." },
        { id: "base", value: 139, returnPct: 12, premise: "Utilization holds near the recent range." },
        { id: "bull", value: 171, returnPct: 38, premise: "Earnings quality improves with utilization." },
      ],
      sparkline: [102, 105, 104, 108, 111, 109, 114, 116, 121, 120, 124.2],
    },
    {
      id: "US:AEON",
      market: "US",
      ticker: "AEON",
      company: "AEON Biopharma, Inc.",
      sector: "Biotechnology",
      capTier: "micro",
      currency: "USD",
      price: 2.14,
      dailyChangePct: -1.9,
      priority: 86,
      status: "new_evidence",
      owner: null,
      queueReason: "Biopharma filing differential adds a new capital-structure question.",
      keyChange:
        "New filing language changes dilution sensitivity while the clinical catalyst remains inside the monitored window.",
      thesisSummary:
        "Potential asymmetry exists, but only after reconciling warrant overhang and near-term funding requirements.",
      invalidation: "The financing structure materially expands fully diluted shares before the catalyst.",
      catalyst: { label: "Regulatory milestone", window: "11 days", daysAway: 11, confidence: "inferred" },
      factors: { quality: 48, value: 71, momentum: 54, risk: 84 },
      evidence: {
        freshness: "fresh",
        sourceCount: 15,
        counterCount: 6,
        coveragePct: 88,
        knownAt: "2026-07-14T19:40:00Z",
        items: [
          {
            id: "aeon-8k",
            source: "SEC",
            title: "Current report and attached financing terms",
            publishedAt: "2026-07-14",
            purpose: "supporting",
            confidence: "primary",
          },
          {
            id: "aeon-s1",
            source: "SEC",
            title: "Registration statement dilution reconciliation",
            publishedAt: "2026-07-10",
            purpose: "counter",
            confidence: "derived",
          },
        ],
      },
      liquidity: { averageDailyValue: "$1.1m", capacity: "$64k", exitDays: 3.8 },
      flags: ["Dilution overhang", "Sub-$5 security", "Binary catalyst"],
      scenarios: [
        { id: "bear", value: 0.82, returnPct: -62, premise: "Financing precedes validation." },
        { id: "base", value: 2.65, returnPct: 24, premise: "Catalyst arrives without added dilution." },
        { id: "bull", value: 5.1, returnPct: 138, premise: "Milestone materially de-risks the program." },
      ],
      sparkline: [1.8, 1.92, 1.88, 2.03, 2.18, 2.11, 2.28, 2.21, 2.17, 2.2, 2.14],
    },
    {
      id: "DSE:SEAPEARL",
      market: "DSE",
      ticker: "SEAPEARL",
      company: "Sea Pearl Beach Resort & Spa",
      sector: "Services & Real Estate",
      capTier: "small",
      currency: "BDT",
      price: 45.0,
      dailyChangePct: 2.27,
      priority: 82,
      status: "monitoring",
      owner: "Nadia Islam",
      queueReason: "Price participation is elevated but official evidence is not yet contemporaneous.",
      keyChange:
        "Market participation accelerated without a same-window material filing, increasing the need for a disciplined evidence review.",
      thesisSummary:
        "Valuation appears below sector, but governance, earnings quality, and source freshness must justify the discount.",
      invalidation: "Fresh official evidence weakens earnings quality or ownership disclosure confidence.",
      catalyst: { label: "Next official filing", window: "18 days", daysAway: 18, confidence: "inferred" },
      factors: { quality: 52, value: 79, momentum: 83, risk: 69 },
      evidence: {
        freshness: "aging",
        sourceCount: 12,
        counterCount: 3,
        coveragePct: 76,
        knownAt: "2026-07-09T09:15:00Z",
        items: [
          {
            id: "sea-q3",
            source: "DSE",
            title: "Most recent quarterly financial disclosure",
            publishedAt: "2026-04-29",
            purpose: "context",
            confidence: "primary",
          },
          {
            id: "sea-owner",
            source: "DSE",
            title: "Reported ownership history",
            publishedAt: "2026-06-30",
            purpose: "counter",
            confidence: "primary",
          },
        ],
      },
      liquidity: { averageDailyValue: "৳2.6cr", capacity: "৳11.7l", exitDays: 2.2 },
      flags: ["Extended momentum", "Evidence aging"],
      scenarios: [
        { id: "bear", value: 31, returnPct: -31, premise: "Discount reflects earnings quality." },
        { id: "base", value: 49, returnPct: 9, premise: "Current earnings normalize without impairment." },
        { id: "bull", value: 62, returnPct: 38, premise: "Earnings quality closes the sector discount." },
      ],
      sparkline: [38.1, 38.4, 38.2, 39.1, 40.3, 41.8, 42.4, 43.1, 44.2, 44.0, 45.0],
    },
    {
      id: "US:VEEE",
      market: "US",
      ticker: "VEEE",
      company: "Twin Vee PowerCats Co.",
      sector: "Recreational Products",
      capTier: "penny",
      currency: "USD",
      price: 1.33,
      dailyChangePct: 0.8,
      priority: 78,
      status: "needs_review",
      owner: null,
      queueReason: "Capital structure and implementation capacity require reconciliation.",
      keyChange:
        "The security is now researchable, but the evidence pack has unresolved fully diluted share and liquidity assumptions.",
      thesisSummary:
        "Operational optionality is secondary until capital structure and practical position capacity are verified.",
      invalidation: "Liquidity falls below minimum capacity or dilution assumptions cannot be reconciled.",
      catalyst: { label: "Quarterly filing", window: "26 days", daysAway: 26, confidence: "inferred" },
      factors: { quality: 39, value: 66, momentum: 43, risk: 91 },
      evidence: {
        freshness: "gap",
        sourceCount: 9,
        counterCount: 5,
        coveragePct: 61,
        knownAt: "2026-07-11T20:00:00Z",
        items: [
          {
            id: "veee-10q",
            source: "SEC",
            title: "Latest quarterly filing",
            publishedAt: "2026-05-14",
            purpose: "context",
            confidence: "primary",
          },
          {
            id: "veee-cap",
            source: "SEC",
            title: "Capital structure reconciliation",
            publishedAt: "2026-07-11",
            purpose: "counter",
            confidence: "derived",
          },
        ],
      },
      liquidity: { averageDailyValue: "$310k", capacity: "$14k", exitDays: 5.4 },
      flags: ["Penny stock", "Low capacity", "Evidence gap"],
      scenarios: [
        { id: "bear", value: 0.48, returnPct: -64, premise: "Dilution dominates operating progress." },
        { id: "base", value: 1.5, returnPct: 13, premise: "Liquidity and share count remain stable." },
        { id: "bull", value: 2.9, returnPct: 118, premise: "Demand inflects without new financing." },
      ],
      sparkline: [1.45, 1.39, 1.42, 1.36, 1.31, 1.28, 1.3, 1.34, 1.31, 1.32, 1.33],
    },
    {
      id: "DSE:EBL",
      market: "DSE",
      ticker: "EBL",
      company: "Eastern Bank PLC",
      sector: "Bank",
      capTier: "large",
      currency: "BDT",
      price: 24.6,
      dailyChangePct: 0.41,
      priority: 74,
      status: "monitoring",
      owner: "Arif Rahman",
      queueReason: "Quality and income remain attractive while ownership evidence is mixed.",
      keyChange:
        "Reported institutional ownership improved while sponsor ownership softened; the net interpretation remains conditional.",
      thesisSummary:
        "A quality-income case with better implementation capacity, but the thesis requires credit-quality and ownership monitoring.",
      invalidation: "Asset-quality deterioration offsets income and valuation support.",
      catalyst: { label: "Quarterly earnings", window: "21 days", daysAway: 21, confidence: "inferred" },
      factors: { quality: 81, value: 69, momentum: 48, risk: 33 },
      evidence: {
        freshness: "fresh",
        sourceCount: 31,
        counterCount: 4,
        coveragePct: 97,
        knownAt: "2026-07-12T08:15:00Z",
        items: [
          {
            id: "ebl-owner",
            source: "DSE",
            title: "Reported ownership disclosure history",
            publishedAt: "2026-06-30",
            purpose: "supporting",
            confidence: "primary",
          },
          {
            id: "ebl-fin",
            source: "DSE",
            title: "Annual and quarterly financial trajectory",
            publishedAt: "2026-04-28",
            purpose: "context",
            confidence: "primary",
          },
        ],
      },
      liquidity: { averageDailyValue: "৳5.8cr", capacity: "৳31.6l", exitDays: 1.1 },
      flags: ["Credit-cycle exposure"],
      scenarios: [
        { id: "bear", value: 20.8, returnPct: -15, premise: "Credit costs rise faster than income." },
        { id: "base", value: 27.4, returnPct: 11, premise: "Asset quality remains controlled." },
        { id: "bull", value: 32.1, returnPct: 30, premise: "ROE improves with stable credit costs." },
      ],
      sparkline: [23.8, 24.0, 23.9, 24.2, 24.4, 24.3, 24.5, 24.8, 24.7, 24.5, 24.6],
    },
    {
      id: "DSE:ITC",
      market: "DSE",
      ticker: "ITC",
      company: "IT Consultants PLC",
      sector: "IT",
      capTier: "small",
      currency: "BDT",
      price: 52.2,
      dailyChangePct: 1.6,
      priority: 71,
      status: "new_evidence",
      owner: "Nadia Islam",
      queueReason: "A high-volume flat base has moved into confirmation monitoring.",
      keyChange:
        "Participation expanded after a multi-week base, but the research process must separate technical confirmation from business evidence.",
      thesisSummary:
        "The pattern is actionable for research only if liquidity persists and official evidence supports operating strength.",
      invalidation: "Breakout participation fades or price loses the base on elevated volume.",
      catalyst: { label: "Pattern confirmation", window: "2 days", daysAway: 2, confidence: "confirmed" },
      factors: { quality: 61, value: 57, momentum: 91, risk: 55 },
      evidence: {
        freshness: "aging",
        sourceCount: 14,
        counterCount: 2,
        coveragePct: 79,
        knownAt: "2026-07-13T12:30:00Z",
        items: [
          {
            id: "itc-bars",
            source: "Market data",
            title: "Flat-base and participation confirmation",
            publishedAt: "2026-07-14",
            purpose: "supporting",
            confidence: "derived",
          },
          {
            id: "itc-dse",
            source: "DSE",
            title: "Latest official company evidence",
            publishedAt: "2026-06-20",
            purpose: "counter",
            confidence: "primary",
          },
        ],
      },
      liquidity: { averageDailyValue: "৳3.2cr", capacity: "৳15.2l", exitDays: 1.9 },
      flags: ["Momentum extension", "Technical-led evidence"],
      scenarios: [
        { id: "bear", value: 44.1, returnPct: -16, premise: "Breakout fails back into the base." },
        { id: "base", value: 57.8, returnPct: 11, premise: "Participation persists without extension." },
        { id: "bull", value: 67.2, returnPct: 29, premise: "Official evidence confirms operating momentum." },
      ],
      sparkline: [41.8, 42.1, 41.9, 42.3, 42.0, 42.5, 44.7, 47.1, 49.6, 51.3, 52.2],
    },
    {
      id: "US:QTTB",
      market: "US",
      ticker: "QTTB",
      company: "Q32 Bio Inc.",
      sector: "Biotechnology",
      capTier: "small",
      currency: "USD",
      price: 3.76,
      dailyChangePct: -0.6,
      priority: 68,
      status: "monitoring",
      owner: "Maya Chen",
      queueReason: "Catalyst proximity is increasing while ownership evidence remains lagged.",
      keyChange:
        "The catalyst window has narrowed, but quarterly institutional filings cannot confirm current positioning.",
      thesisSummary:
        "Monitor the event asymmetry without treating delayed 13F ownership as a current-flow signal.",
      invalidation: "Catalyst timing moves outside the mandate or financing risk rises before the event.",
      catalyst: { label: "Program update", window: "14 days", daysAway: 14, confidence: "inferred" },
      factors: { quality: 55, value: 62, momentum: 49, risk: 76 },
      evidence: {
        freshness: "fresh",
        sourceCount: 17,
        counterCount: 5,
        coveragePct: 86,
        knownAt: "2026-07-14T20:00:00Z",
        items: [
          {
            id: "qttb-sec",
            source: "SEC",
            title: "Recent filing and program disclosure",
            publishedAt: "2026-07-13",
            purpose: "supporting",
            confidence: "primary",
          },
          {
            id: "qttb-13f",
            source: "SEC 13F",
            title: "Lagged institutional ownership context",
            publishedAt: "2026-05-15",
            purpose: "context",
            confidence: "primary",
          },
        ],
      },
      liquidity: { averageDailyValue: "$1.9m", capacity: "$112k", exitDays: 2.7 },
      flags: ["Binary catalyst", "Ownership lag"],
      scenarios: [
        { id: "bear", value: 1.35, returnPct: -64, premise: "Program update disappoints." },
        { id: "base", value: 4.4, returnPct: 17, premise: "Update preserves program probability." },
        { id: "bull", value: 8.2, returnPct: 118, premise: "Evidence materially improves probability." },
      ],
      sparkline: [3.2, 3.4, 3.35, 3.51, 3.68, 3.61, 3.82, 3.74, 3.8, 3.78, 3.76],
    },
  ],
};
