"""ticker_buzz_daily

Revision ID: 2c377ce5ddbc
Revises: 41a90e2a5dc4
"""

import sqlalchemy as sa
from alembic import op

revision = "2c377ce5ddbc"
down_revision = "41a90e2a5dc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_buzz_daily",
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("posts_24h", sa.Integer(), nullable=False),
        sa.Column("reactions_24h", sa.Integer(), nullable=False),
        sa.Column("replies_24h", sa.Integer(), nullable=False),
        sa.Column("watchers_total", sa.Integer(), nullable=False),
        sa.Column("unique_viewers_24h", sa.Integer(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("market", "code", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticker_buzz_daily")
    # ### end Alembic commands ###
