"""page_view_events

Revision ID: 981c6f2c6b0e
Revises: 2c377ce5ddbc
"""

import sqlalchemy as sa
from alembic import op

revision = "981c6f2c6b0e"
down_revision = "2c377ce5ddbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_view_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("session_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_page_view_market_code_created",
        "page_view_events",
        ["market", "code", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_page_view_market_code_created", table_name="page_view_events")
    op.drop_table("page_view_events")
    # ### end Alembic commands ###
