"""ticker_analytics

Revision ID: be08a2401a8b
Revises: 11f74a1f0aac
"""

import sqlalchemy as sa
from alembic import op

revision = "be08a2401a8b"
down_revision = "11f74a1f0aac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_analytics",
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("last_close", sa.Float(), nullable=False),
        sa.Column("sma_50", sa.Float(), nullable=True),
        sa.Column("sma_200", sa.Float(), nullable=True),
        sa.Column("above_sma_50", sa.Boolean(), nullable=True),
        sa.Column("above_sma_200", sa.Boolean(), nullable=True),
        sa.Column("rsi_14", sa.Float(), nullable=True),
        sa.Column("atr_14", sa.Float(), nullable=True),
        sa.Column("nearest_support", sa.Float(), nullable=True),
        sa.Column("nearest_resistance", sa.Float(), nullable=True),
        sa.Column("week52_high", sa.Float(), nullable=True),
        sa.Column("week52_low", sa.Float(), nullable=True),
        sa.Column("pct_from_52w_high", sa.Float(), nullable=True),
        sa.Column("pct_from_52w_low", sa.Float(), nullable=True),
        sa.Column("avg_volume_20", sa.Float(), nullable=True),
        sa.Column("relative_volume", sa.Float(), nullable=True),
        sa.Column("cmf_20", sa.Float(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("market", "code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticker_analytics")
    # ### end Alembic commands ###
