"""announcements

Revision ID: c5bb55bcd935
Revises: fc6ff6bedbef
"""

import sqlalchemy as sa
from alembic import op

revision = "c5bb55bcd935"
down_revision = "fc6ff6bedbef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(op.f("ix_announcements_category"), "announcements", ["category"], unique=False)
    op.create_index(op.f("ix_announcements_code"), "announcements", ["code"], unique=False)
    op.create_index(op.f("ix_announcements_market"), "announcements", ["market"], unique=False)
    op.create_index(
        op.f("ix_announcements_published_at"), "announcements", ["published_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcements_published_at"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_market"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_code"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_category"), table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
