"""symbol_is_hidden

Revision ID: def0949b2174
Revises: be08a2401a8b
"""

import sqlalchemy as sa
from alembic import op

revision = "def0949b2174"
down_revision = "be08a2401a8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "symbols", sa.Column("is_hidden", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("symbols", "is_hidden")
    # ### end Alembic commands ###
