"""signal_events_and_post_kind

Revision ID: fc6ff6bedbef
Revises: e5f6a7b8c9d0
"""

import sqlalchemy as sa
from alembic import op

revision = "fc6ff6bedbef"
down_revision = "e5f6a7b8c9d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("agent", sa.String(length=48), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("occurrence_key", sa.String(length=48), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "market", "code", "event_type", "occurrence_key", name="uq_signal_event"
        ),
    )
    op.create_index(op.f("ix_signal_events_code"), "signal_events", ["code"], unique=False)
    op.create_index(op.f("ix_signal_events_market"), "signal_events", ["market"], unique=False)
    op.add_column(
        "posts", sa.Column("kind", sa.String(length=8), server_default="user", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "kind")
    op.drop_index(op.f("ix_signal_events_market"), table_name="signal_events")
    op.drop_index(op.f("ix_signal_events_code"), table_name="signal_events")
    op.drop_table("signal_events")
    # ### end Alembic commands ###
